version: "3"
services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000


# docker-compose up --build   
# docker-compose down
# note: -d:背景執行, --build:重新部屬